name: test
on: [push]
jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
     steps:
       - name: execute remot script
         uses: manjulive89/fe-docker@master
         with:
           host: "45.63.88.234"
           username: "root"
           password: "j#M9eA*scB7[D9a6"
           port: "22"
           run: ls
