name: test
on: [push]
jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
     steps:
       - name: execute remot script
         uses: manjulive89/fe-docker@master
         with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.SERVER_USERNAME }}
           password: ${{ secrets.SERVER_PASSWORD }}
           port: ${{ secrets.PORT }}
           script: sh /root/deploy.sh
